### PR TITLE
Enable sentry

### PR DESCRIPTION
**Pull request by psoleckimoj**

### CODE REVIEW

**Review by spikeheap — APPROVED** [review]
For posterity, this is for https://trello.com/c/7oAh13Kt/1767-sentry-is-not-fully-enabled-on-the-node-frontend. 

This looks good 🙌. It'll be nice to start capturing these errors & getting alerted on them 🥳 .

Should we clean up the old reference to Sentry in https://github.com/ministryofjustice/prisoner-content-hub-frontend/blob/main/server.js#L3 in this PR? I agree that it should live here rather than in `server.js` 👍

**Comment by psoleckimoj** [comment]
Good spot @spikeheap I hadn't even spotted it was there 😆

**Review by LucasCairns — APPROVED** [review]
LGTM 👍

**Review by davidthomas22 — DISMISSED** [review]
LGTM

**Review by LucasCairns — DISMISSED** [review]
👍

**Review by davidthomas22 — APPROVED** [review]
LGTM

**Pull request merged**
