### PR TITLE
Add CP outgoing IPs to allowed in Ingress

### PR DESCRIPTION
**Pull request by psoleckimoj**
- Required for health-kick to work

### CODE REVIEW

**Comment by spikeheap** [comment]
I was just about to paste this into Slack:

> Should we make the long allow-list string -> array conversion a must-have for the next PR we see on this code?

Could we refactor this long single element into an array? It's certainly becoming a bit unwieldy :)

**Comment by psoleckimoj** [comment]
@spikeheap happy for any pointers, the docs say it's a comma separated list but my google skills maybe limited 😄

**Comment by psoleckimoj** [comment]
https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#whitelist-source-range

**Comment by psoleckimoj** [comment]
Just realised we can do this when passing the values into the ingress 😄

**Comment by spikeheap** [comment]
:+1: The whereabouts-api has a good example:
- https://github.com/ministryofjustice/whereabouts-api/blob/main/helm_deploy/whereabouts-api/templates/ingress.yaml#L15
- https://github.com/ministryofjustice/whereabouts-api/blob/main/helm_deploy/values-prod.yaml#L28

**Comment by psoleckimoj** [comment]
Ooo I like that!

**Review by davidthomas22 — DISMISSED** [review]
LGTM

**Review by davidthomas22 — APPROVED** [review]
LGTM

**Review by LucasCairns — APPROVED** [review]
b-e-a-utiful! 👍

**Pull request merged**
