### PR TITLE
Add Christmas crossword

### PR DESCRIPTION
**Pull request by LucasCairns**
### Context

> Does this issue have a Trello card?

https://trello.com/c/hADmC1bR/1760-create-christmas-crosswords-schedule-release

### Intent

> What changes are introduced by this PR that correspond to the above card?

Added the route `/games/christmas-crossword` and applied the initial list of Christmas clues

> Would this PR benefit from screenshots?

Screenshot 2020-12-16 at 11 54 49

### Considerations

> Is there any additional information that would help when reviewing this PR?

This change simply copies existing code for the crossword and modifies the clue list to be Christmas theme, this means that we should avoid major refactoring and presumably retain the same amount of test coverage.

> Are there any steps required when merging/deploying this PR?

N/A

### Checklist

- [x] This PR contains **only** changes related to the above card
- [ ] Tested in Development

### CODE REVIEW

**Comment by psoleckimoj** [comment]
Maybe not the right time to do it but seeing as the only change is the word list and this is just on a different route, is there no way to pull that out into a config file and just change the config based on route?

**Comment by LucasCairns** [comment]
Definitely something we should look in to, but for this PR I have tried to avoid any major code changes, so we can simply throw this away after the festive period

**Review by spikeheap — APPROVED** [review]
This looks good :+1:. I've tested it on dev and the success/reset flow works nicely.

:+1: to copy/pasting to reduce the effort right now. That said, it'd be worth throwing a card into Trello to cover that refactor so next year we can just add a route/question list if we need a new crossword. Great suggestion @psoleckimoj

**Review by psoleckimoj — DISMISSED** [review]
LGTM!

**Review by davidthomas22 — APPROVED** [review]
LGTM

**Review by davidthomas22 — APPROVED** [review]
LGTM

**Pull request merged**
