### PR TITLE
Make failed auth url configurable

### PR DESCRIPTION
**Pull request by psoleckimoj**
- Add config to Helm
- Add config to config file
- All url to be injected to allow testing

### CODE REVIEW

**Comment by spikeheap** [comment]
Do we want to tightly couple our auth flow with the CMS? I can see it has some benefits by allowing other members of the team to add content, but it _feels_ like a frontend system flow, and feels distinct from CMS content. 

As an example, I would expect the auth failure to be reported correctly if we switched to a new CMS, or had a test environment with no content.

**Comment by psoleckimoj** [comment]
@spikeheap it's configurable? It's not tied to anything 😕

**Review by davidthomas22 — APPROVED** [review]
LGTM

**Comment by spikeheap** [comment]
> @spikeheap it's configurable? It's not tied to anything 😕

What I'm getting at is that it won't work without those CMS pages, so our frontend auth flow demands a specific piece of content exist in the CMS for the auth flow to work (or rather, fail) correctly.

What makes me uncomfortable is that we're taking something that (I believe) is an integral part of the frontend auth flow, and shifting that concern into the CMS. 

As an example, we've talked about being able to fire up a vanilla version of the Drupal instance for development/test environments. To have a functional (albeit empty) site, this change introduces the need for us to create at least one page.

**Pull request closed without merging**
