### PR TITLE
feature/1332-adding-thestudio-prison-to-establishments

### PR DESCRIPTION
**Pull request by jonhindle**
### Context

> Does this issue have a Trello card?
https://trello.com/c/u2BObqF3/1332-2-the-studio-technical-set-up

> If this is an issue, do we have steps to reproduce?
n/a

### Intent

> What changes are introduced by this PR that correspond to the above card?
Adding `thestudio` prison.

> Would this PR benefit from screenshots?
n/a

### Considerations

> Is there any additional information that would help when reviewing this PR?
n/a

> Are there any steps required when merging/deploying this PR?
Ensure the drupal id is updated.

### Checklist

- [ ] This PR contains **only** changes related to the above card
- [ ] Tests have been added/updated to cover the change
- [ ] Documentation has been updated where appropriate
- [ ] Tested in Development

### CODE REVIEW

**Comment by jonhindle** [comment]
@BarryGeeMOJ you just need to add the drupal id in place of the `0000` before merging

**Review by BarryGeeMOJ — DISMISSED** [review]
lgtm

**Review by leonk — DISMISSED** [review]
lgtm

**Review by BarryGeeMOJ — APPROVED** [review]
lgtm

**Review by BarryGeeMOJ — APPROVED** [review]

**Pull request merged**
